[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.19"
[rpc_endpoints]
mainnet = "${RPC_MAINNET}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
