[profile.default]
evm_version = "cancun"
libs = ['lib']
optimizer = true
optimizer_runs = 10000
out = 'out'
solc = "0.8.20"
src = 'src'
[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
[etherscan]
mainnet = {key = "${ETHERSCAN_API_KEY}"}

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
